spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mybatis.mapper-locations=classpath: mapper/*.xml
  type-aliases-package: com.ruanyuan.crm_master.pojo
server:
  port: 8181
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
